modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${sources}"
logoFile="${mod_id}-icon.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="mdcdi1315_base_mods_lib"
type="required"
versionRange="[${base_mods_lib_version},)"
ordering="AFTER"
side="BOTH"